FROM ubuntu:20.04

ENV DEBIAN_FRONTEND=noninteractive

# Add user
RUN adduser --quiet --disabled-password q2rad && usermod -a -G audio q2rad

# This fix: libGL error: No matching fbConfigs or visuals found
ENV LIBGL_ALWAYS_INDIRECT=1
ENV XDG_RUNTIME_DIR=/tmp/runtime-q2rad

RUN apt-get update
RUN apt-get install -y python3-pip
RUN apt-get install -y python3-pyqt5
RUN python3 -m pip install pip setuptools --upgrade
RUN pip install pyqt6
RUN pip install PyQt6-QScintilla
RUN pip install q2rad

WORKDIR /home/q2rad
